import Head from 'next/head'
import {BsLightbulb,BsLightbulbOff} from 'react-icons/bs'
import {AiFillGithub,AiFillMediumCircle,AiFillLinkedin} from 'react-icons/ai'



export default function Home() {
  return (
    <>
      <Head>
        <title>Antony Ni Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-blue-200 px-10">
        <section className="bg-blue-200 min-h-screen ">
          <nav className ="p-2 mb-12 flex justify-between">
            <h1 className="text-2xl">	&#60;antonyni&#62;</h1>
            <ul className="flex items-center">
              <li>
                <AiFillGithub className="text-2xl text-blue-400"/>
              </li>
              <li>
                <AiFillMediumCircle className="ml-3 text-2xl text-blue-400"/>
              </li>
              <li className="pr-10 ml-3 text-2xl text-blue-400">
                <AiFillLinkedin/>
              </li>
              <li>
                <BsLightbulbOff className="cursor-pointer text-xl"/>
              </li>
              <li>
                <a className="bg-blue-300 text-white px-4 py-1 rounded-md ml-8 text-xl" href="#">&#60;resume/&#62;</a>
              </li>

            </ul>
      
          </nav>
          <div className ="text-center">
            <h2 className="text-xl">Hi I'm Antony!</h2>
            <p className="px-20 mx-40">Software Engineer with a passion for cool animations. Full-stack development with a focus on CSS, HTML, and
             JavaScript. Agile enthusiast. Avid podcast, fitness, and video game junkie with a growth mindset. Chronically bad singer. </p>
          </div>
          


        </section>
        <h1 className="text-2xl ml-2">	&#60;/antonyni&#62;</h1>
      </main>
    </>
  )
}
